/* eslint-disable @typescript-eslint/naming-convention */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Meta/Categories": {
    /** Gets the list of available StopPoint additional information categories */
    get: operations["StopPoint_MetaCategories"];
  };
  "/Meta/StopTypes": {
    /** Gets the list of available StopPoint types */
    get: operations["StopPoint_MetaStopTypes"];
  };
  "/Meta/Modes": {
    /** Gets the list of available StopPoint modes */
    get: operations["StopPoint_MetaModes"];
  };
  "/{ids}": {
    /** Gets a list of StopPoints corresponding to the given list of stop ids. */
    get: operations["StopPoint_GetByPathIdsQueryIncludeCrowdingData"];
  };
  "/{id}/placeTypes": {
    /** Get a list of places corresponding to a given id and place types. */
    get: operations["StopPoint_GetByPathIdQueryPlaceTypes"];
  };
  "/{id}/Crowding/{line}": {
    /** Gets all the Crowding data (static) for the StopPointId, plus crowding data for a given line and optionally a particular direction. */
    get: operations["StopPoint_CrowdingByPathIdPathLineQueryDirection"];
  };
  "/Type/{types}": {
    /** Gets all stop points of a given type */
    get: operations["StopPoint_GetByTypeByPathTypes"];
  };
  "/Type/{types}/page/{page}": {
    /** Gets all the stop points of given type(s) with a page number */
    get: operations["StopPoint_GetByTypeWithPaginationByPathTypesPathPage"];
  };
  "/ServiceTypes": {
    /** Gets the service types for a given stoppoint */
    get: operations["StopPoint_GetServiceTypesByQueryIdQueryLineIdsQueryModes"];
  };
  "/{id}/Arrivals": {
    /** Gets the list of arrival predictions for the given stop point id */
    get: operations["StopPoint_ArrivalsByPathId"];
  };
  "/{id}/ArrivalDepartures": {
    /** Gets the list of arrival and departure predictions for the given stop point id (overground and tfl rail only) */
    get: operations["StopPoint_ArrivalDeparturesByPathIdQueryLineIds"];
  };
  "/{id}/CanReachOnLine/{lineId}": {
    /** Gets Stopoints that are reachable from a station/line combination. */
    get: operations["StopPoint_ReachableFromByPathIdPathLineIdQueryServiceTypes"];
  };
  "/{id}/Route": {
    /** Returns the route sections for all the lines that service the given stop point ids */
    get: operations["StopPoint_RouteByPathIdQueryServiceTypes"];
  };
  "/Mode/{modes}/Disruption": {
    /** Gets a distinct list of disrupted stop points for the given modes */
    get: operations["StopPoint_DisruptionByModeByPathModesQueryIncludeRouteBlockedStops"];
  };
  "/{ids}/Disruption": {
    /** Gets all disruptions for the specified StopPointId, plus disruptions for any child Naptan records it may have. */
    get: operations["StopPoint_DisruptionByPathIdsQueryGetFamilyQueryIncludeRouteBlockedStopsQuer"];
  };
  "/{id}/DirectionTo/{toStopPointId}": {
    /** Returns the canonical direction, "inbound" or "outbound", for a given pair of stop point Ids in the direction from -&gt; to. */
    get: operations["StopPoint_DirectionByPathIdPathToStopPointIdQueryLineId"];
  };
  "/": {
    /** Gets a list of StopPoints within {radius} by the specified criteria */
    get: operations["StopPoint_GetByGeoPointByQueryLatQueryLonQueryStopTypesQueryRadiusQueryUseSt"];
  };
  "/Mode/{modes}": {
    /** Gets a list of StopPoints filtered by the modes available at that StopPoint. */
    get: operations["StopPoint_GetByModeByPathModesQueryPage"];
  };
  "/Search/{query}": {
    /** Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code. */
    get: operations["StopPoint_SearchByPathQueryQueryModesQueryFaresOnlyQueryMaxResultsQueryLines"];
  };
  "/Search": {
    /** Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code. */
    get: operations["StopPoint_SearchByQueryQueryQueryModesQueryFaresOnlyQueryMaxResultsQueryLine"];
  };
  "/Sms/{id}": {
    /** Gets a StopPoint for a given sms code. */
    get: operations["StopPoint_GetBySmsByPathIdQueryOutput"];
  };
  "/{stopPointId}/TaxiRanks": {
    /** Gets a list of taxi ranks corresponding to the given stop point id. */
    get: operations["StopPoint_GetTaxiRanksByIdsByPathStopPointId"];
  };
  "/{stopPointId}/CarParks": {
    /** Get car parks corresponding to the given stop point id. */
    get: operations["StopPoint_GetCarParksByIdByPathStopPointId"];
  };
  "/*": {
    /** Forwards any remaining requests to the back-end */
    get: operations["Forward_Proxy"];
  };
}

export interface components {
  schemas: {
    Tfl: {
      category: string;
      availableKeys: string[];
    };
    "Tfl-2": {
      isTflService: boolean;
      isFarePaying: boolean;
      isScheduledService: boolean;
      modeName: string;
    };
    "Tfl-3": {
      /** @description Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc. */
      timeSlice: string;
      /**
       * Format: int32
       * @description Count of passenger flow towards a platform
       */
      value: number;
    };
    "Tfl-4": {
      /** @description The Line Name e.g. "Victoria" */
      line: string;
      /** @description Direction of the Line e.g. NB, SB, WB etc. */
      lineDirection: string;
      /** @description Direction displayed on the platform e.g. NB, SB, WB etc. */
      platformDirection: string;
      /** @description Direction in regards to Journey Planner i.e. inbound or outbound */
      direction: string;
      /** @description Naptan of the adjacent station */
      naptanTo: string;
      /** @description Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc. */
      timeSlice: string;
      /**
       * Format: int32
       * @description Scale between 1-6,
       *              1 = Very quiet, 2 = Quiet, 3 = Fairly busy, 4 = Busy, 5 = Very busy, 6 = Exceptionally busy
       */
      value: number;
    };
    "Tfl-5": {
      /** @description Busiest times at a station (static information) */
      passengerFlows: components["schemas"]["Tfl-3"][];
      /** @description Train Loading on a scale 1-6, 1 being "Very quiet" and 6 being "Exceptionally busy" (static information) */
      trainLoadings: components["schemas"]["Tfl-4"][];
    };
    "Tfl-6": {
      id: string;
      name: string;
      uri: string;
      fullName: string;
      type: string;
      crowding: components["schemas"]["Tfl-5"];
      /** @enum {string} */
      routeType:
        | "Unknown"
        | "All"
        | "Cycle Superhighways"
        | "Quietways"
        | "Cycleways"
        | "Mini-Hollands"
        | "Central London Grid"
        | "Streetspace Route";
      /** @enum {string} */
      status:
        | "Unknown"
        | "All"
        | "Open"
        | "In Progress"
        | "Planned"
        | "Planned - Subject to feasibility and consultation."
        | "Not Open";
    };
    "Tfl-7": {
      naptanIdReference: string;
      stationAtcoCode: string;
      lineIdentifier: string[];
    };
    "Tfl-8": {
      modeName: string;
      lineIdentifier: string[];
    };
    "Tfl-9": {
      category: string;
      key: string;
      sourceSystemKey: string;
      value: string;
      /** Format: date-time */
      modified: string;
    };
    "Tfl-10": {
      /** @description A unique identifier. */
      id: string;
      /** @description The unique location of this resource. */
      url: string;
      /** @description A human readable name. */
      commonName: string;
      /**
       * Format: double
       * @description The distance of the place from its search point, if this is the result
       *             of a geographical search, otherwise zero.
       */
      distance: number;
      /** @description The type of Place. See /Place/Meta/placeTypes for possible values. */
      placeType: string;
      /** @description A bag of additional key/value pairs with extra information about this place. */
      additionalProperties: components["schemas"]["Tfl-9"][];
      children: components["schemas"]["Tfl-10"][];
      childrenUrls: string[];
      /**
       * Format: double
       * @description WGS84 latitude of the location.
       */
      lat: number;
      /**
       * Format: double
       * @description WGS84 longitude of the location.
       */
      lon: number;
    };
    "Tfl-11": {
      naptanId: string;
      platformName: string;
      /** @description The indicator of the stop point e.g. "Stop K" */
      indicator: string;
      /** @description The stop letter, if it could be cleansed from the Indicator e.g. "K" */
      stopLetter: string;
      modes: string[];
      icsCode: string;
      smsCode: string;
      stopType: string;
      stationNaptan: string;
      accessibilitySummary: string;
      hubNaptanCode: string;
      lines: components["schemas"]["Tfl-6"][];
      lineGroup: components["schemas"]["Tfl-7"][];
      lineModeGroups: components["schemas"]["Tfl-8"][];
      fullName: string;
      naptanMode: string;
      status: boolean;
      /** @description A unique identifier. */
      id: string;
      /** @description The unique location of this resource. */
      url: string;
      /** @description A human readable name. */
      commonName: string;
      /**
       * Format: double
       * @description The distance of the place from its search point, if this is the result
       *             of a geographical search, otherwise zero.
       */
      distance: number;
      /** @description The type of Place. See /Place/Meta/placeTypes for possible values. */
      placeType: string;
      /** @description A bag of additional key/value pairs with extra information about this place. */
      additionalProperties: components["schemas"]["Tfl-9"][];
      children: components["schemas"]["Tfl-10"][];
      childrenUrls: string[];
      /**
       * Format: double
       * @description WGS84 latitude of the location.
       */
      lat: number;
      /**
       * Format: double
       * @description WGS84 longitude of the location.
       */
      lon: number;
    };
    "Tfl-12": {
      name: string;
      uri: string;
    };
    "Tfl-13": {
      serviceType: components["schemas"]["Tfl-12"];
      stopServesServiceType: boolean;
    };
    "Tfl-14": {
      lineName: string;
      lineSpecificServiceTypes: components["schemas"]["Tfl-13"][];
    };
    "Tfl-15": {
      countdownServerAdjustment: string;
      /** Format: date-time */
      source: string;
      /** Format: date-time */
      insert: string;
      /** Format: date-time */
      read: string;
      /** Format: date-time */
      sent: string;
      /** Format: date-time */
      received: string;
    };
    /** @description DTO to capture the prediction details */
    "Tfl-16": {
      /** @description The identitier for the prediction */
      id: string;
      /**
       * Format: int32
       * @description The type of the operation (1: is new or has been updated, 2: should be deleted from any client cache)
       */
      operationType: number;
      /** @description The actual vehicle in transit (for train modes, the leading car of the rolling set) */
      vehicleId: string;
      /** @description Identifier for the prediction */
      naptanId: string;
      /** @description Station name */
      stationName: string;
      /** @description Unique identifier for the Line */
      lineId: string;
      /** @description Line Name */
      lineName: string;
      /** @description Platform name (for bus, this is the stop letter) */
      platformName: string;
      /** @description Direction (unified to inbound/outbound) */
      direction: string;
      /** @description Bearing (between 0 to 359) */
      bearing: string;
      /** @description Naptan Identifier for the prediction's destination */
      destinationNaptanId: string;
      /** @description Name of the destination */
      destinationName: string;
      /**
       * Format: date-time
       * @description Timestamp for when the prediction was inserted/modified (source column drives what objects are broadcast on each iteration)
       */
      timestamp: string;
      /**
       * Format: int32
       * @description Prediction of the Time to station in seconds
       */
      timeToStation: number;
      /** @description The current location of the vehicle. */
      currentLocation: string;
      /** @description Routing information or other descriptive text about the path of the vehicle towards the destination */
      towards: string;
      /**
       * Format: date-time
       * @description The expected arrival time of the vehicle at the stop/station
       */
      expectedArrival: string;
      /**
       * Format: date-time
       * @description The expiry time for the prediction
       */
      timeToLive: string;
      /** @description The mode name of the station/line the prediction relates to */
      modeName: string;
      timing: components["schemas"]["Tfl-15"];
    };
    /** @description DTO to capture the prediction details */
    "Tfl-17": {
      /** @description Platform name (for bus, this is the stop letter) */
      platformName: string;
      /** @description Naptan Identifier for the prediction's destination */
      destinationNaptanId: string;
      /** @description Name of the destination */
      destinationName: string;
      /** @description Identifier for the prediction */
      naptanId: string;
      /** @description Station name */
      stationName: string;
      /**
       * Format: date-time
       * @description Estimated time of arrival
       */
      estimatedTimeOfArrival: string;
      /**
       * Format: date-time
       * @description Estimated time of arrival
       */
      scheduledTimeOfArrival: string;
      /**
       * Format: date-time
       * @description Estimated time of arrival
       */
      estimatedTimeOfDeparture: string;
      /**
       * Format: date-time
       * @description Estimated time of arrival
       */
      scheduledTimeOfDeparture: string;
      /** @description Estimated time of arrival */
      minutesAndSecondsToArrival: string;
      /** @description Estimated time of arrival */
      minutesAndSecondsToDeparture: string;
      /** @description Reason for cancellation or delay */
      cause: string;
      /**
       * @description Status of departure
       * @enum {string}
       */
      departureStatus:
        | "OnTime"
        | "Delayed"
        | "Cancelled"
        | "NotStoppingAtStation";
      timing: components["schemas"]["Tfl-15"];
    };
    "Tfl-18": {
      naptanId: string;
      lineId: string;
      mode: string;
      /** Format: date-time */
      validFrom: string;
      /** Format: date-time */
      validTo: string;
      direction: string;
      routeSectionName: string;
      lineString: string;
      isActive: boolean;
      serviceType: string;
      vehicleDestinationText: string;
      destinationName: string;
    };
    "Tfl-19": {
      atcoCode: string;
      /** Format: date-time */
      fromDate: string;
      /** Format: date-time */
      toDate: string;
      description: string;
      commonName: string;
      type: string;
      mode: string;
      stationAtcoCode: string;
      appearance: string;
      additionalInformation: string;
    };
    /** @description A paged response containing StopPoints */
    "Tfl-20": {
      /** @description The centre latitude/longitude of this list of StopPoints */
      centrePoint: number[];
      /** @description Collection of stop points */
      stopPoints: components["schemas"]["Tfl-11"][];
      /**
       * Format: int32
       * @description The maximum size of the page in this response i.e. the maximum number of StopPoints
       */
      pageSize: number;
      /**
       * Format: int32
       * @description The total number of StopPoints available across all pages
       */
      total: number;
      /**
       * Format: int32
       * @description The index of this page
       */
      page: number;
    };
    "Tfl-21": {
      id: string;
      url: string;
      name: string;
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
    };
    "Tfl-22": {
      query: string;
      /** Format: int32 */
      from: number;
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      provider: string;
      /** Format: int32 */
      total: number;
      matches: components["schemas"]["Tfl-21"][];
      /** Format: double */
      maxScore: number;
    };
    System: { [key: string]: unknown };
    Get200ApplicationJsonResponse: { [key: string]: unknown };
    MetaCategoriesGet200ApplicationJsonResponse: components["schemas"]["Tfl"][];
    MetaCategoriesGet200TextJsonResponse: components["schemas"]["Tfl"][];
    MetaCategoriesGet200ApplicationXmlResponse: components["schemas"]["Tfl"][];
    MetaCategoriesGet200TextXmlResponse: components["schemas"]["Tfl"][];
    MetaStopTypesGet200ApplicationJsonResponse: string[];
    MetaStopTypesGet200TextJsonResponse: string[];
    MetaStopTypesGet200ApplicationXmlResponse: string[];
    MetaStopTypesGet200TextXmlResponse: string[];
    MetaModesGet200ApplicationJsonResponse: components["schemas"]["Tfl-2"][];
    MetaModesGet200TextJsonResponse: components["schemas"]["Tfl-2"][];
    MetaModesGet200ApplicationXmlResponse: components["schemas"]["Tfl-2"][];
    MetaModesGet200TextXmlResponse: components["schemas"]["Tfl-2"][];
    "ids-Get200ApplicationJsonResponse": components["schemas"]["Tfl-11"][];
    "ids-Get200TextJsonResponse": components["schemas"]["Tfl-11"][];
    "ids-Get200ApplicationXmlResponse": components["schemas"]["Tfl-11"][];
    "ids-Get200TextXmlResponse": components["schemas"]["Tfl-11"][];
    "id-PlaceTypesGet200ApplicationJsonResponse": components["schemas"]["Tfl-10"][];
    "id-PlaceTypesGet200TextJsonResponse": components["schemas"]["Tfl-10"][];
    "id-PlaceTypesGet200ApplicationXmlResponse": components["schemas"]["Tfl-10"][];
    "id-PlaceTypesGet200TextXmlResponse": components["schemas"]["Tfl-10"][];
    "id-Crowding-line-Get200ApplicationJsonResponse": components["schemas"]["Tfl-11"][];
    "id-Crowding-line-Get200TextJsonResponse": components["schemas"]["Tfl-11"][];
    "id-Crowding-line-Get200ApplicationXmlResponse": components["schemas"]["Tfl-11"][];
    "id-Crowding-line-Get200TextXmlResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Get200ApplicationJsonResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Get200TextJsonResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Get200ApplicationXmlResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Get200TextXmlResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Page-page-Get200ApplicationJsonResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Page-page-Get200TextJsonResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Page-page-Get200ApplicationXmlResponse": components["schemas"]["Tfl-11"][];
    "Type-types-Page-page-Get200TextXmlResponse": components["schemas"]["Tfl-11"][];
    ServiceTypesGet200ApplicationJsonResponse: components["schemas"]["Tfl-14"][];
    ServiceTypesGet200TextJsonResponse: components["schemas"]["Tfl-14"][];
    ServiceTypesGet200ApplicationXmlResponse: components["schemas"]["Tfl-14"][];
    ServiceTypesGet200TextXmlResponse: components["schemas"]["Tfl-14"][];
    "id-ArrivalsGet200ApplicationJsonResponse": components["schemas"]["Tfl-16"][];
    "id-ArrivalsGet200TextJsonResponse": components["schemas"]["Tfl-16"][];
    "id-ArrivalsGet200ApplicationXmlResponse": components["schemas"]["Tfl-16"][];
    "id-ArrivalsGet200TextXmlResponse": components["schemas"]["Tfl-16"][];
    "id-ArrivalDeparturesGet200ApplicationJsonResponse": components["schemas"]["Tfl-17"][];
    "id-ArrivalDeparturesGet200TextJsonResponse": components["schemas"]["Tfl-17"][];
    "id-ArrivalDeparturesGet200ApplicationXmlResponse": components["schemas"]["Tfl-17"][];
    "id-ArrivalDeparturesGet200TextXmlResponse": components["schemas"]["Tfl-17"][];
    "id-CanReachOnLine-lineId-Get200ApplicationJsonResponse": components["schemas"]["Tfl-11"][];
    "id-CanReachOnLine-lineId-Get200TextJsonResponse": components["schemas"]["Tfl-11"][];
    "id-CanReachOnLine-lineId-Get200ApplicationXmlResponse": components["schemas"]["Tfl-11"][];
    "id-CanReachOnLine-lineId-Get200TextXmlResponse": components["schemas"]["Tfl-11"][];
    "id-RouteGet200ApplicationJsonResponse": components["schemas"]["Tfl-18"][];
    "id-RouteGet200TextJsonResponse": components["schemas"]["Tfl-18"][];
    "id-RouteGet200ApplicationXmlResponse": components["schemas"]["Tfl-18"][];
    "id-RouteGet200TextXmlResponse": components["schemas"]["Tfl-18"][];
    "Mode-modes-DisruptionGet200ApplicationJsonResponse": components["schemas"]["Tfl-19"][];
    "Mode-modes-DisruptionGet200TextJsonResponse": components["schemas"]["Tfl-19"][];
    "Mode-modes-DisruptionGet200ApplicationXmlResponse": components["schemas"]["Tfl-19"][];
    "Mode-modes-DisruptionGet200TextXmlResponse": components["schemas"]["Tfl-19"][];
    "ids-DisruptionGet200ApplicationJsonResponse": components["schemas"]["Tfl-19"][];
    "ids-DisruptionGet200TextJsonResponse": components["schemas"]["Tfl-19"][];
    "ids-DisruptionGet200ApplicationXmlResponse": components["schemas"]["Tfl-19"][];
    "ids-DisruptionGet200TextXmlResponse": components["schemas"]["Tfl-19"][];
    "id-DirectionTo-toStopPointId-Get200ApplicationJsonResponse": string;
    "id-DirectionTo-toStopPointId-Get200TextJsonResponse": string;
    "id-DirectionTo-toStopPointId-Get200ApplicationXmlResponse": string;
    "id-DirectionTo-toStopPointId-Get200TextXmlResponse": string;
    "stopPointId-TaxiRanksGet200ApplicationJsonResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-TaxiRanksGet200TextJsonResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-TaxiRanksGet200ApplicationXmlResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-TaxiRanksGet200TextXmlResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-CarParksGet200ApplicationJsonResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-CarParksGet200TextJsonResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-CarParksGet200ApplicationXmlResponse": components["schemas"]["Tfl-10"][];
    "stopPointId-CarParksGet200TextXmlResponse": components["schemas"]["Tfl-10"][];
  };
}

export interface operations {
  /** Gets the list of available StopPoint additional information categories */
  StopPoint_MetaCategories: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaCategoriesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaCategoriesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaCategoriesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaCategoriesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the list of available StopPoint types */
  StopPoint_MetaStopTypes: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaStopTypesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaStopTypesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaStopTypesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaStopTypesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the list of available StopPoint modes */
  StopPoint_MetaModes: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaModesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaModesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaModesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaModesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets a list of StopPoints corresponding to the given list of stop ids. */
  StopPoint_GetByPathIdsQueryIncludeCrowdingData: {
    parameters: {
      path: {
        /**
         * A comma-separated list of stop point ids (station naptan code e.g. 940GZZLUASL). Max. approx. 20 ids.
         *             You can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name.
         */
        ids: string;
      };
      query: {
        /** Include the crowding data (static). To Filter further use: /StopPoint/{ids}/Crowding/{line} */
        includeCrowdingData?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ids-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["ids-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["ids-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["ids-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Get a list of places corresponding to a given id and place types. */
  StopPoint_GetByPathIdQueryPlaceTypes: {
    parameters: {
      path: {
        /** A naptan id for a stop point (station naptan code e.g. 940GZZLUASL). */
        id: string;
      };
      query: {
        /** A comcomma-separated value representing the place types. */
        placeTypes: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-PlaceTypesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-PlaceTypesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["id-PlaceTypesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-PlaceTypesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets all the Crowding data (static) for the StopPointId, plus crowding data for a given line and optionally a particular direction. */
  StopPoint_CrowdingByPathIdPathLineQueryDirection: {
    parameters: {
      path: {
        /** The Naptan id of the stop */
        id: string;
        /** A particular line e.g. victoria, circle, northern etc. */
        line: string;
      };
      query: {
        /** The direction of travel. Can be inbound or outbound. */
        direction: "inbound" | "outbound" | "all";
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-Crowding-line-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-Crowding-line-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["id-Crowding-line-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-Crowding-line-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets all stop points of a given type */
  StopPoint_GetByTypeByPathTypes: {
    parameters: {
      path: {
        /**
         * A comma-separated list of the types to return. Max. approx. 12 types.
         *             A list of valid stop types can be obtained from the StopPoint/meta/stoptypes endpoint.
         */
        types: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Type-types-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["Type-types-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["Type-types-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["Type-types-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets all the stop points of given type(s) with a page number */
  StopPoint_GetByTypeWithPaginationByPathTypesPathPage: {
    parameters: {
      path: {
        types: string;
        /** Format - int32. */
        page: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Type-types-Page-page-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["Type-types-Page-page-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["Type-types-Page-page-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["Type-types-Page-page-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the service types for a given stoppoint */
  StopPoint_GetServiceTypesByQueryIdQueryLineIdsQueryModes: {
    parameters: {
      query: {
        /** The Naptan id of the stop */
        id: string;
        /** The lines which contain the given Naptan id (all lines relevant to the given stoppoint if empty) */
        lineIds?: unknown[];
        /** The modes which the lines are relevant to (all if empty) */
        modes?: unknown[];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceTypesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["ServiceTypesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["ServiceTypesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["ServiceTypesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the list of arrival predictions for the given stop point id */
  StopPoint_ArrivalsByPathId: {
    parameters: {
      path: {
        /** A StopPoint id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) */
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-ArrivalsGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-ArrivalsGet200TextJsonResponse"];
          "application/xml": components["schemas"]["id-ArrivalsGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-ArrivalsGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the list of arrival and departure predictions for the given stop point id (overground and tfl rail only) */
  StopPoint_ArrivalDeparturesByPathIdQueryLineIds: {
    parameters: {
      path: {
        /** A StopPoint id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) */
        id: string;
      };
      query: {
        /** A comma-separated list of line ids e.g. tfl-rail, london-overground */
        lineIds: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-ArrivalDeparturesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-ArrivalDeparturesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["id-ArrivalDeparturesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-ArrivalDeparturesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets Stopoints that are reachable from a station/line combination. */
  StopPoint_ReachableFromByPathIdPathLineIdQueryServiceTypes: {
    parameters: {
      path: {
        /** The id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) of the stop point to filter by */
        id: string;
        /** Line id of the line to filter by (e.g. victoria) */
        lineId: string;
      };
      query: {
        /** A comma-separated list of service types to filter on. If not specified. Supported values: Regular, Night. Defaulted to 'Regular' if not specified */
        serviceTypes?: "Regular" | "Night";
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-CanReachOnLine-lineId-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-CanReachOnLine-lineId-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["id-CanReachOnLine-lineId-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-CanReachOnLine-lineId-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Returns the route sections for all the lines that service the given stop point ids */
  StopPoint_RouteByPathIdQueryServiceTypes: {
    parameters: {
      path: {
        /** A stop point id (station naptan codes e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) */
        id: string;
      };
      query: {
        /** A comma-separated list of service types to filter on. If not specified. Supported values: Regular, Night. Defaulted to 'Regular' if not specified */
        serviceTypes?: "Regular" | "Night";
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-RouteGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-RouteGet200TextJsonResponse"];
          "application/xml": components["schemas"]["id-RouteGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-RouteGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets a distinct list of disrupted stop points for the given modes */
  StopPoint_DisruptionByModeByPathModesQueryIncludeRouteBlockedStops: {
    parameters: {
      path: {
        /** A comma-seperated list of modes e.g. tube,dlr */
        modes: string;
      };
      query: {
        includeRouteBlockedStops?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Mode-modes-DisruptionGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["Mode-modes-DisruptionGet200TextJsonResponse"];
          "application/xml": components["schemas"]["Mode-modes-DisruptionGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["Mode-modes-DisruptionGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets all disruptions for the specified StopPointId, plus disruptions for any child Naptan records it may have. */
  StopPoint_DisruptionByPathIdsQueryGetFamilyQueryIncludeRouteBlockedStopsQuer: {
    parameters: {
      path: {
        /**
         * A comma-seperated list of stop point ids. Max. approx. 20 ids.
         *             You can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name.
         */
        ids: string;
      };
      query: {
        /** Specify true to return disruptions for entire family, or false to return disruptions for just this stop point. Defaults to false. */
        getFamily?: boolean;
        includeRouteBlockedStops?: boolean;
        /** Specify true to associate all disruptions with parent stop point. (Only applicable when getFamily is true). */
        flattenResponse?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ids-DisruptionGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["ids-DisruptionGet200TextJsonResponse"];
          "application/xml": components["schemas"]["ids-DisruptionGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["ids-DisruptionGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Returns the canonical direction, "inbound" or "outbound", for a given pair of stop point Ids in the direction from -&gt; to. */
  StopPoint_DirectionByPathIdPathToStopPointIdQueryLineId: {
    parameters: {
      path: {
        /** Originating stop id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) */
        id: string;
        /** Destination stop id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) */
        toStopPointId: string;
      };
      query: {
        /** Optional line id filter e.g. victoria */
        lineId?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["id-DirectionTo-toStopPointId-Get200ApplicationJsonResponse"];
          "text/json": components["schemas"]["id-DirectionTo-toStopPointId-Get200TextJsonResponse"];
          "application/xml": components["schemas"]["id-DirectionTo-toStopPointId-Get200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["id-DirectionTo-toStopPointId-Get200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets a list of StopPoints within {radius} by the specified criteria */
  StopPoint_GetByGeoPointByQueryLatQueryLonQueryStopTypesQueryRadiusQueryUseSt: {
    parameters: {
      query: {
        /** Format - double. the latitude of the centre of the bounding circle */
        lat: number;
        /** Format - double. the longitude of the centre of the bounding circle */
        lon: number;
        /** a list of stopTypes that should be returned (a list of valid stop types can be obtained from the StopPoint/meta/stoptypes endpoint) */
        stopTypes: string;
        /** Format - int32. the radius of the bounding circle in metres (default : 200) */
        radius?: number;
        /** Re-arrange the output into a parent/child hierarchy */
        useStopPointHierarchy?: boolean;
        /** the list of modes to search (comma separated mode names e.g. tube,dlr) */
        modes?: unknown[];
        /** an optional list of comma separated property categories to return in the StopPoint's property bag. If null or empty, all categories of property are returned. Pass the keyword "none" to return no properties (a valid list of categories can be obtained from the /StopPoint/Meta/categories endpoint) */
        categories?: unknown[];
        /** true to return the lines that each stop point serves as a nested resource */
        returnLines?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-20"];
          "text/json": components["schemas"]["Tfl-20"];
          "application/xml": components["schemas"]["Tfl-20"];
          "text/xml": components["schemas"]["Tfl-20"];
        };
      };
    };
  };
  /** Gets a list of StopPoints filtered by the modes available at that StopPoint. */
  StopPoint_GetByModeByPathModesQueryPage: {
    parameters: {
      path: {
        /** A comma-seperated list of modes e.g. tube,dlr */
        modes: string;
      };
      query: {
        /** Format - int32. The data set page to return. Page 1 equates to the first 1000 stop points, page 2 equates to 1001-2000 etc. Must be entered for bus mode as data set is too large. */
        page?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-20"];
          "text/json": components["schemas"]["Tfl-20"];
          "application/xml": components["schemas"]["Tfl-20"];
          "text/xml": components["schemas"]["Tfl-20"];
        };
      };
    };
  };
  /** Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code. */
  StopPoint_SearchByPathQueryQueryModesQueryFaresOnlyQueryMaxResultsQueryLines: {
    parameters: {
      path: {
        /** The query string, case-insensitive. Leading and trailing wildcards are applied automatically. */
        query: string;
      };
      query: {
        /** An optional, parameter separated list of the modes to filter by */
        modes?: unknown[];
        /** True to only return stations in that have Fares data available for single fares to another station. */
        faresOnly?: boolean;
        /**
         * Format - int32. An optional result limit, defaulting to and with a maximum of 50. Since children of the stop point heirarchy are returned for matches,
         *             it is possible that the flattened result set will contain more than 50 items.
         */
        maxResults?: number;
        /** An optional, parameter separated list of the lines to filter by */
        lines?: unknown[];
        /** If true, returns results including HUBs. */
        includeHubs?: boolean;
        /** If the national-rail mode is included, this flag will filter the national rail stations so that only those operated by TfL are returned */
        tflOperatedNationalRailStationsOnly?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-22"];
          "text/json": components["schemas"]["Tfl-22"];
          "application/xml": components["schemas"]["Tfl-22"];
          "text/xml": components["schemas"]["Tfl-22"];
        };
      };
    };
  };
  /** Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code. */
  StopPoint_SearchByQueryQueryQueryModesQueryFaresOnlyQueryMaxResultsQueryLine: {
    parameters: {
      query: {
        /** The query string, case-insensitive. Leading and trailing wildcards are applied automatically. */
        query: string;
        /** An optional, parameter separated list of the modes to filter by */
        modes?: unknown[];
        /** True to only return stations in that have Fares data available for single fares to another station. */
        faresOnly?: boolean;
        /**
         * Format - int32. An optional result limit, defaulting to and with a maximum of 50. Since children of the stop point heirarchy are returned for matches,
         *             it is possible that the flattened result set will contain more than 50 items.
         */
        maxResults?: number;
        /** An optional, parameter separated list of the lines to filter by */
        lines?: unknown[];
        /** If true, returns results including HUBs. */
        includeHubs?: boolean;
        /** If the national-rail mode is included, this flag will filter the national rail stations so that only those operated by TfL are returned */
        tflOperatedNationalRailStationsOnly?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-22"];
          "text/json": components["schemas"]["Tfl-22"];
          "application/xml": components["schemas"]["Tfl-22"];
          "text/xml": components["schemas"]["Tfl-22"];
        };
      };
    };
  };
  /** Gets a StopPoint for a given sms code. */
  StopPoint_GetBySmsByPathIdQueryOutput: {
    parameters: {
      path: {
        /** A 5-digit Countdown Bus Stop Code e.g. 73241, 50435, 56334. */
        id: string;
      };
      query: {
        /** If set to "web", a 302 redirect to relevant website bus stop page is returned. Valid values are : web. All other values are ignored. */
        output?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["System"];
          "text/json": components["schemas"]["System"];
          "application/xml": components["schemas"]["System"];
          "text/xml": components["schemas"]["System"];
        };
      };
    };
  };
  /** Gets a list of taxi ranks corresponding to the given stop point id. */
  StopPoint_GetTaxiRanksByIdsByPathStopPointId: {
    parameters: {
      path: {
        /** stopPointId is required to get the taxi ranks. */
        stopPointId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["stopPointId-TaxiRanksGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["stopPointId-TaxiRanksGet200TextJsonResponse"];
          "application/xml": components["schemas"]["stopPointId-TaxiRanksGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["stopPointId-TaxiRanksGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Get car parks corresponding to the given stop point id. */
  StopPoint_GetCarParksByIdByPathStopPointId: {
    parameters: {
      path: {
        /** stopPointId is required to get the car parks. */
        stopPointId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["stopPointId-CarParksGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["stopPointId-CarParksGet200TextJsonResponse"];
          "application/xml": components["schemas"]["stopPointId-CarParksGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["stopPointId-CarParksGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Forwards any remaining requests to the back-end */
  Forward_Proxy: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Get200ApplicationJsonResponse"];
        };
      };
    };
  };
}

export interface external {}
